### Site metadata

title: HappyKiddo Support site
description: HappyKiddo Support site

### Build settings

url: http://support.happykiddo.io/
baseurl:

theme: just-the-docs

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - LICENSE
  - Makefile
  - sample.png
  - README.md

search_enabled: false
